import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // ── Stitch Light Theme: Daylight Atelier ─────────────────
        "surface-variant": "#e9e8e2",
        "tertiary-fixed-dim": "#c4c7ca",
        "primary": "#9c602a",
        "accent-amber": "#b3743b",
        "accent-ochre": "#965a26",
        "background": "#faf9f5",
        "surface-container-highest": "#e2e3df",
        "paper-surface": "#faf9f5",
        "paper-base": "#faf9f5",
        "paper-sidebar": "#f0efe9",
        "paper-container": "#eaeae5",
        "on-error": "#ffffff",
        "on-tertiary-fixed-variant": "#43474a",
        "secondary-fixed-dim": "#ffb77f",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#e0e3e6",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#181c1f",
        "primary-fixed": "#ffdcc2",
        "surface-container-high": "#e8e8e4",
        "inverse-surface": "#11181c",
        "on-error-container": "#93000a",
        "tertiary": "#595c60",
        "on-surface-variant": "#4a555a",
        "primary-container": "#b3743b",
        "ink-primary": "#11181c",
        "ink-secondary": "#2c3437",
        "ink-muted": "#6a7378",
        "amber-wash": "#f6eee3",
        "inverse-primary": "#ffb77b",
        "hairline-subtle": "#ecece6",
        "on-secondary-container": "#77410e",
        "surface-container-low": "#f6f5f0",
        "on-primary-container": "#ffffff",
        "on-primary-fixed": "#2e1500",
        "surface-dim": "#dadad6",
        "inverse-on-surface": "#f1f1ed",
        "secondary-container": "#f2eee4",
        "on-secondary-fixed-variant": "#6d3905",
        "surface-container-lowest": "#ffffff",
        "surface": "#faf9f5",
        "secondary-fixed": "#ffdcc4",
        "on-primary-fixed-variant": "#6c3a03",
        "surface-container": "#fbfbfa",
        "on-tertiary": "#ffffff",
        "on-surface": "#11181c",
        "on-secondary": "#ffffff",
        "on-secondary-fixed": "#2f1500",
        "hairline-rule": "#e5e4de",
        "on-background": "#1a1c1a",
        "surface-tint": "#89511b",
        "primary-fixed-dim": "#ffb77b",
        "on-tertiary-container": "#fbfcff",
        "tertiary-container": "#717578",
        "outline": "#8b9498",
        "secondary": "#8a501d",
        "surface-bright": "#faf9f5",
        "outline-variant": "#e2e1da",
        "error": "#ba1a1a",

        // ── Stitch Login Dark Theme tokens ───────────────────────
        "cosmic-bg": "#0b1013",
        "cosmic-surface": "#0e1417",
        "cosmic-container-low": "#12181c",
        "cosmic-container": "#182025",
        "cosmic-container-high": "#222a2f",
        "paper-card": "#f7f6f1",
        "paper-input": "#ffffff",
        "paper-border": "#e3ded3",
        "outline-paper": "#d8d3c5",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "margin": "2.5rem",
        "space-sm": "0.5rem",
        "gutter": "1.5rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "headline-xl": ["Newsreader", "DM Serif Display", "serif"],
        "headline-xl-mobile": ["Newsreader", "DM Serif Display", "serif"],
        "headline-lg": ["Newsreader", "DM Serif Display", "serif"],
        "headline-lg-mobile": ["Newsreader", "DM Serif Display", "serif"],
        "headline-md": ["Newsreader", "DM Serif Display", "serif"],
        "headline-sm": ["Newsreader", "DM Serif Display", "serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label-lg": ["JetBrains Mono", "IBM Plex Mono", "monospace"],
        "label-md": ["JetBrains Mono", "IBM Plex Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "IBM Plex Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["3.25rem", { lineHeight: "3.75rem", letterSpacing: "-0.02em", fontWeight: "400" }],
        "headline-xl-mobile": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg": ["2.25rem", { lineHeight: "2.75rem", letterSpacing: "-0.015em", fontWeight: "400" }],
        "headline-lg-mobile": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-md": ["1.75rem", { lineHeight: "2.25rem", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-sm": ["1.25rem", { lineHeight: "1.75rem", letterSpacing: "0em", fontWeight: "500" }],
        "body-lg": ["1.125rem", { lineHeight: "1.875rem", letterSpacing: "-0.005em", fontWeight: "400" }],
        "body-md": ["0.9375rem", { lineHeight: "1.5rem", letterSpacing: "0em", fontWeight: "400" }],
        "body-sm": ["0.8125rem", { lineHeight: "1.25rem", letterSpacing: "0em", fontWeight: "400" }],
        "label-lg": ["0.8125rem", { lineHeight: "1.125rem", letterSpacing: "0.06em", fontWeight: "500" }],
        "label-md": ["0.6875rem", { lineHeight: "1rem", letterSpacing: "0.08em", fontWeight: "500" }],
        "label-sm": ["0.625rem", { lineHeight: "0.875rem", letterSpacing: "0.08em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
  future: {
    hoverOnlyWhenSupported: true,
  },
};
export default config;
